// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSeatServer.Models;

namespace RedSeatServer.Migrations
{
    [DbContext(typeof(RedseatDbContext))]
    [Migration("20200722093554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4");

            modelBuilder.Entity("RedSeatServer.Models.Download", b =>
                {
                    b.Property<int>("DownloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownloaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("downloaded")
                        .HasColumnType("INTEGER");

                    b.Property<long>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("DownloadId");

                    b.HasIndex("DownloadStatus");

                    b.HasIndex("DownloaderId");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("RedSeatServer.Models.Downloader", b =>
                {
                    b.Property<int>("DownloaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloaderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("DownloaderId");

                    b.ToTable("Downloaders");
                });

            modelBuilder.Entity("RedSeatServer.Models.Download", b =>
                {
                    b.HasOne("RedSeatServer.Models.Downloader", "Downloader")
                        .WithMany("Downloads")
                        .HasForeignKey("DownloaderId");
                });
#pragma warning restore 612, 618
        }
    }
}
